<?php

use Illuminate\Database\Seeder;

class BarangaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('barangays')->insert([
        		['name' => 'Brgy. 1, San Lorenzo'],
				['name' => 'Brgy. 2, Santa Joaquina'],
				['name' => 'Brgy. 3, Nuestra Señora del Rosario'],
				['name' => 'Brgy. 4, San Guillermo'],
				['name' => 'Brgy. 5, San Pedro'],
				['name' => 'Brgy. 6, San Agustin'],
				['name' => 'Brgy. 7-A, Nuestra Señora del Natividad'],
				['name' => 'Brgy. 7-B, Nuestra Señora del Natividad'],
				['name' => 'Brgy. 8, San Vicente'],
				['name' => 'Brgy. 9, Santa Angela'],
				['name' => 'Brgy. 10, San Jose'],
				['name' => 'Brgy. 11, Santa Balbina'],
				['name' => 'Brgy. 12, San Isidro'],
				['name' => 'Brgy. 13, Nuestra Señora de Visitacion'],
				['name' => 'Brgy. 14, Santo Tomas'],
				['name' => 'Brgy. 15, San Guillermo'],
				['name' => 'Brgy. 16, San Jacinto'],
				['name' => 'Brgy. 17, San Francisco'],
				['name' => 'Brgy. 18, San Quirino'],
				['name' => 'Brgy. 19, Santa Marcela'],
				['name' => 'Brgy. 20, San Miguel'],
				['name' => 'Brgy. 21, San Pedro'],
				['name' => 'Brgy. 22, San Andres'],
				['name' => 'Brgy. 23, San Matias'],
				['name' => 'Brgy. 24, Nuestra Señora de Consolacion'],
				['name' => 'Brgy. 25, Santa Cayetana'],
				['name' => 'Brgy. 26, San Marcelino'],
				['name' => 'Brgy. 27, Nuestra Señora de Soledad'],
				['name' => 'Brgy. 28, San Bernardo'],
				['name' => 'Brgy. 29, Santo Tomas'],
				['name' => 'Brgy. 30-A, Suyo'],
				['name' => 'Brgy. 30-B, Santa Maria'],
				['name' => 'Brgy. 31, Talingaan'],
				['name' => 'Brgy. 32-A, La Paz East'],
				['name' => 'Brgy. 32-B, La Paz West'],
				['name' => 'Brgy. 32-C, La Paz East'],
				['name' => 'Brgy. 33-A, La Paz Proper'],
				['name' => 'Brgy. 33-B, La Paz Proper'],
				['name' => 'Brgy. 34-A, Gabu Norte West'],
				['name' => 'Brgy. 34-B, Gabu Norte East'],
				['name' => 'Brgy. 35, Gabu Sur'],
				['name' => 'Brgy. 36, Araniw'],
				['name' => 'Brgy. 37, Calayab'],
				['name' => 'Brgy. 38-A, Mangato East'],
				['name' => 'Brgy. 38-B, Mangato West'],
				['name' => 'Brgy. 39, Santa Rosa'],
				['name' => 'Brgy. 40, Balatong'],
				['name' => 'Brgy. 41, Balacad'],
				['name' => 'Brgy. 42, Apaya'],
				['name' => 'Brgy. 43, Cavit'],
				['name' => 'Brgy. 44, Zamboanga'],
				['name' => 'Brgy. 45, Tangid'],
				['name' => 'Brgy. 46, Nalbo'],
				['name' => 'Brgy. 47, Bengcag'],
				['name' => 'Brgy. 48-A, Cabungaan North'],
				['name' => 'Brgy. 48-B, Cabungaan South'],
				['name' => 'Brgy. 49-A, Darayday'],
				['name' => 'Brgy. 49-B, Raraburan'],
				['name' => 'Brgy. 50, Buttong'],
				['name' => 'Brgy. 51-A, Nangalisan East'],
				['name' => 'Brgy. 51-B, Nangalisan West'],
				['name' => 'Brgy. 52-A, San Mateo'],
				['name' => 'Brgy. 52-B, Lataag'],
				['name' => 'Brgy. 53, Rioeng'],
				['name' => 'Brgy. 54-A, Camangaan'],
				['name' => 'Brgy. 54-B, Lagui-Sail'],
				['name' => 'Brgy. 55-A, Barit-Pandan'],
				['name' => 'Brgy. 55-B, Salet-Bulangon'],
				['name' => 'Brgy. 55-C, Vira'],
				['name' => 'Brgy. 56-A, Bacsil North'],
				['name' => 'Brgy. 56-B, Bacsil South'],
				['name' => 'Brgy. 57, Pila'],
				['name' => 'Brgy. 58, Casili'],
				['name' => 'Brgy. 59-A, Dibua South'],
				['name' => 'Brgy. 59-B, Dibua North'],
				['name' => 'Brgy. 60-A, Caaoacan'],
				['name' => 'Brgy. 60-B, Madiladig'],
				['name' => 'Brgy. 61, Cataban'],
				['name' => 'Brgy. 62-A, Navotas North'],
				['name' => 'Brgy. 62-B, Navotas South'],
        	]);
    }
}
